site_name: common-lisp-libraries
theme:
    name: readthedocs
    collapse_by_default: false
    highlightjs: true
    hljs_languages:
        - lisp
    navigation_depth: 4
    sticky_navigation: false
    prev_next_buttons_location: none
include_search_page: true
nav:
    - index: index.md
    - Defacto libraries:
      - alexandria.md
      - bordeaux-threads.md
      - cl-ppcre.md
      - cl-who.md
      - fiveam.md
      - hunchentoot.md
      - iterate.md
      - postmodern.md
      - quicklisp.md
    - Not yet defacto:
      - numcl.md
      - unix-opts.md
      - utilities.md
plugins:
    - search
extra_css: [extra.css]